[
  {
    id: 'debmaster',
    name: 'Mastercard Débito',
    payment_type_id: 'debit_card',
    status: 'active',
    secure_thumbnail: 'https://www.mercadopago.com/org-img/MP3/API/logos/debmaster.gif',
    thumbnail: 'https://www.mercadopago.com/org-img/MP3/API/logos/debmaster.gif',
    deferred_capture: 'unsupported',
    settings: [[Object]],
    additional_info_needed: ['cardholder_name'],
    min_allowed_amount: 5,
    max_allowed_amount: 300000,
    accreditation_time: 2880,
    financial_institutions: [],
    processing_modes: ['aggregator']
  },
  {
    id: 'clabe',
    name: 'STP',
    payment_type_id: 'bank_transfer',
    status: 'active',
    secure_thumbnail: 'https://www.mercadopago.com/org-img/MP3/API/logos/clabe.gif',
    thumbnail: 'http://img.mlstatic.com/org-img/MP3/API/logos/clabe.gif',
    deferred_capture: 'does_not_apply',
    settings: [],
    additional_info_needed: [],
    min_allowed_amount: 1,
    max_allowed_amount: 10000000,
    accreditation_time: 0,
    financial_institutions: [[Object]],
    processing_modes: ['aggregator']
  },
  {
    id: 'paycash',
    name: 'PayCash',
    payment_type_id: 'ticket',
    status: 'active',
    secure_thumbnail: 'https://www.mercadopago.com/org-img/MP3/API/logos/paycash.gif',
    thumbnail: 'https://www.mercadopago.com/org-img/MP3/API/logos/paycash.gif',
    deferred_capture: 'unsupported',
    settings: [],
    additional_info_needed: ['entity_type', 'identification_number', 'identification_type'],
    min_allowed_amount: 20,
    max_allowed_amount: 10000,
    accreditation_time: 0,
    financial_institutions: [],
    processing_modes: ['aggregator']
  },
  {
    id: 'master',
    name: 'Mastercard',
    payment_type_id: 'credit_card',
    status: 'active',
    secure_thumbnail: 'https://http2.mlstatic.com/storage/logos-api-admin/9cf818e0-723a-11f0-a459-cf21d0937aeb-l.svg',
    thumbnail: 'https://http2.mlstatic.com/storage/logos-api-admin/9cf818e0-723a-11f0-a459-cf21d0937aeb-l.svg',
    deferred_capture: 'supported',
    settings: [[Object]],
    additional_info_needed: ['cardholder_name'],
    min_allowed_amount: 5,
    max_allowed_amount: 300000,
    accreditation_time: 2880,
    financial_institutions: [],
    processing_modes: ['aggregator']
  },
  {
    id: 'visa',
    name: 'Visa',
    payment_type_id: 'credit_card',
    status: 'active',
    secure_thumbnail: 'https://www.mercadopago.com/org-img/MP3/API/logos/visa.gif',
    thumbnail: 'http://img.mlstatic.com/org-img/MP3/API/logos/visa.gif',
    deferred_capture: 'supported',
    settings: [[Object]],
    additional_info_needed: ['cardholder_name'],
    min_allowed_amount: 5,
    max_allowed_amount: 300000,
    accreditation_time: 2880,
    financial_institutions: [],
    processing_modes: ['aggregator']
  },
  {
    id: 'master',
    name: 'Mastercard Prepaid',
    payment_type_id: 'prepaid_card',
    status: 'active',
    secure_thumbnail: 'https://www.mercadopago.com/org-img/MP3/API/logos/master.gif',
    thumbnail: 'http://img.mlstatic.com/org-img/MP3/API/logos/master.gif',
    deferred_capture: 'supported',
    settings: [[Object]],
    additional_info_needed: ['cardholder_name'],
    min_allowed_amount: 5,
    max_allowed_amount: 200000,
    accreditation_time: 2880,
    financial_institutions: [],
    processing_modes: ['aggregator']
  },
  {
    id: 'visa',
    name: 'Visa Prepaid',
    payment_type_id: 'prepaid_card',
    status: 'active',
    secure_thumbnail: 'https://www.mercadopago.com/org-img/MP3/API/logos/visa.gif',
    thumbnail: 'http://img.mlstatic.com/org-img/MP3/API/logos/visa.gif',
    deferred_capture: 'supported',
    settings: [[Object]],
    additional_info_needed: ['cardholder_name'],
    min_allowed_amount: 5,
    max_allowed_amount: 200000,
    accreditation_time: 2880,
    financial_institutions: [],
    processing_modes: ['aggregator']
  },
  {
    id: 'amex',
    name: 'American Express',
    payment_type_id: 'prepaid_card',
    status: 'active',
    secure_thumbnail: 'https://www.mercadopago.com/org-img/MP3/API/logos/amex.gif',
    thumbnail: 'http://img.mlstatic.com/org-img/MP3/API/logos/amex.gif',
    deferred_capture: 'supported',
    settings: [[Object]],
    additional_info_needed: ['cardholder_name'],
    min_allowed_amount: 5,
    max_allowed_amount: 200000,
    accreditation_time: 2880,
    financial_institutions: [],
    processing_modes: ['aggregator']
  },
  {
    id: 'amex',
    name: 'American Express',
    payment_type_id: 'credit_card',
    status: 'active',
    secure_thumbnail: 'https://www.mercadopago.com/org-img/MP3/API/logos/amex.gif',
    thumbnail: 'http://img.mlstatic.com/org-img/MP3/API/logos/amex.gif',
    deferred_capture: 'supported',
    settings: [[Object]],
    additional_info_needed: ['cardholder_name'],
    min_allowed_amount: 1,
    max_allowed_amount: 300000,
    accreditation_time: 2880,
    financial_institutions: [],
    processing_modes: ['aggregator']
  },
  {
    id: 'debvisa',
    name: 'Visa Débito',
    payment_type_id: 'debit_card',
    status: 'active',
    secure_thumbnail: 'https://www.mercadopago.com/org-img/MP3/API/logos/debvisa.gif',
    thumbnail: 'http://img.mlstatic.com/org-img/MP3/API/logos/debvisa.gif',
    deferred_capture: 'unsupported',
    settings: [[Object]],
    additional_info_needed: ['cardholder_name'],
    min_allowed_amount: 5,
    max_allowed_amount: 300000,
    accreditation_time: 2880,
    financial_institutions: [],
    processing_modes: ['aggregator']
  },
  {
    id: 'oxxo',
    name: 'OXXO',
    payment_type_id: 'ticket',
    status: 'active',
    secure_thumbnail: 'https://http2.mlstatic.com/storage/logos-api-admin/9a6610e0-bfed-11f0-b333-7572333bee91-m.svg',
    thumbnail: 'https://http2.mlstatic.com/storage/logos-api-admin/9a6610e0-bfed-11f0-b333-7572333bee91-m.svg',
    deferred_capture: 'does_not_apply',
    settings: [],
    additional_info_needed: [],
    min_allowed_amount: 5,
    max_allowed_amount: 10000,
    accreditation_time: 2880,
    financial_institutions: [],
    processing_modes: ['aggregator']
  },
  api_response: {
    status: 200,
    headers: [Object: null prototype] {
    date: [Array],
    'content-type': [Array],
    'content-length': [Array],
    connection: [Array],
    'cache-control': [Array],
    'cache-status': [Array],
    'content-encoding': [Array],
    vary: [Array],
    'x-application-name': [Array],
    'x-application-version': [Array],
    'x-deprecated': [Array],
    'x-many-response': [Array],
    'x-api-server-segment': [Array],
    'x-content-type-options': [Array],
    'x-request-id': [Array],
    'x-xss-protection': [Array],
    'strict-transport-security': [Array],
    'access-control-allow-origin': [Array],
    'access-control-allow-headers': [Array],
    'access-control-allow-methods': [Array],
    'access-control-max-age': [Array],
    'timing-allow-origin': [Array]
  }
  }
]