export type CountryConfig = {
  flag: string;
  code: string;
  name: string;
  mask?: string;
};

export const countryList: CountryConfig[] = [
  { flag: "🇺🇸", code: "+1", name: "United States", mask: "(___) ___-____" },
  { flag: "🇬🇧", code: "+44", name: "United Kingdom", mask: "____ ____ ____" },
  { flag: "🇲🇽", code: "+52", name: "Mexico", mask: "(___) ___-____" },
  { flag: "🇦🇷", code: "+54", name: "Argentina", mask: "(___) ___-____" },
  { flag: "🇧🇷", code: "+55", name: "Brazil", mask: "(__) _____-____" },
  { flag: "🇨🇴", code: "+57", name: "Colombia", mask: "(___) ___-____" },
  { flag: "🇨🇱", code: "+56", name: "Chile", mask: "_ ____ ____" },
  "🇵🇪",
  { flag: "🇵🇪", code: "+51", name: "Peru", mask: "(___) ___-___" },
  { flag: "🇻🇪", code: "+58", name: "Venezuela", mask: "(___) ___-____" },
  { flag: "🇬🇹", code: "+502", name: "Guatemala", mask: "____-____" },
  { flag: "🇸🇻", code: "+503", name: "El Salvador", mask: "____-____" },
  { flag: "🇭🇳", code: "+504", name: "Honduras", mask: "____-____" },
  { flag: "🇳🇮", code: "+505", name: "Nicaragua", mask: "____-____" },
  { flag: "🇨🇷", code: "+506", name: "Costa Rica", mask: "____-____" },
  { flag: "🇵🇦", code: "+507", name: "Panama", mask: "____-____" },
  {
    flag: "🇩🇴",
    code: "+809",
    name: "Dominican Republic",
    mask: "(___) ___-____",
  },
  { flag: "🇨🇦", code: "+1", name: "Canada", mask: "(___) ___-____" },
  { flag: "🇪🇸", code: "+34", name: "Spain", mask: "___ __ __ __" },
  { flag: "🇫🇷", code: "+33", name: "France", mask: "__ __ __ __ __" },
  { flag: "🇩🇪", code: "+49", name: "Germany", mask: "___ _______" },
  { flag: "🇮🇹", code: "+39", name: "Italy", mask: "___ ___ ____" },
  { flag: "🇵🇹", code: "+351", name: "Portugal", mask: "___ ___ ___" },
  { flag: "🇳🇱", code: "+31", name: "Netherlands", mask: "__ ____ ____" },
  { flag: "🇧🇪", code: "+32", name: "Belgium", mask: "___ __ __ __" },
  { flag: "🇨🇭", code: "+41", name: "Switzerland", mask: "__ ___ __ __" },
  { flag: "🇦🇹", code: "+43", name: "Austria", mask: "___ _______" },
  { flag: "🇸🇪", code: "+46", name: "Sweden", mask: "___ ___ __ __" },
  { flag: "🇳🇴", code: "+47", name: "Norway", mask: "___ __ ___" },
  { flag: "🇩🇰", code: "+45", name: "Denmark", mask: "__ __ __ __" },
  { flag: "🇫🇮", code: "+358", name: "Finland", mask: "___ _______" },
  { flag: "🇵🇱", code: "+48", name: "Poland", mask: "___ __-__-__" },
  { flag: "🇷🇺", code: "+7", name: "Russia", mask: "(___) __-__-__" },
  { flag: "🇺🇦", code: "+380", name: "Ukraine", mask: "(___) ___-__-__" },
  { flag: "🇹🇷", code: "+90", name: "Turkey", mask: "(___) ___-____" },
  { flag: "🇮🇳", code: "+91", name: "India", mask: "____ __-____" },
  { flag: "🇨🇳", code: "+86", name: "China", mask: "___ ____ ____" },
  { flag: "🇯🇵", code: "+81", name: "Japan", mask: "___-____-____" },
  { flag: "🇰🇷", code: "+82", name: "South Korea", mask: "___-____-____" },
  { flag: "🇦🇺", code: "+61", name: "Australia", mask: "(__) ____ ____" },
  { flag: "🇳🇿", code: "+64", name: "New Zealand", mask: "(___) ___-___" },
  { flag: "🇿🇦", code: "+27", name: "South Africa", mask: "__ ___ ____" },
  { flag: "🇪🇬", code: "+20", name: "Egypt", mask: "(___) ___-____" },
  { flag: "🇮🇱", code: "+972", name: "Israel", mask: "__-___-____" },
  {
    flag: "🇦🇪",
    code: "+971",
    name: "United Arab Emirates",
    mask: "_ ___-____",
  },
  { flag: "🇸🇦", code: "+966", name: "Saudi Arabia", mask: "__ __-____" },
  { flag: "🇶🇦", code: "+974", name: "Qatar", mask: "____-____" },
  { flag: "🇰🇼", code: "+965", name: "Kuwait", mask: "____-____" },
  { flag: "🇧🇭", code: "+973", name: "Bahrain", mask: "____-____" },
  { flag: "🇴🇲", code: "+968", name: "Oman", mask: "____-____" },
  { flag: "🇯🇴", code: "+962", name: "Jordan", mask: "___-____-___" },
  { flag: "🇱🇧", code: "+961", name: "Lebanon", mask: "___-___-___" },
  { flag: "🇸🇾", code: "+963", name: "Syria", mask: "___ ___ ___" },
  { flag: "🇮🇶", code: "+964", name: "Iraq", mask: "(___) ___-___" },
  { flag: "🇮🇷", code: "+98", name: "Iran", mask: "(___) ___-____" },
  { flag: "🇦🇫", code: "+93", name: "Afghanistan", mask: "___ __-___" },
  { flag: "🇵🇰", code: "+92", name: "Pakistan", mask: "(___) ___-____" },
  { flag: "🇧🇩", code: "+880", name: "Bangladesh", mask: "____-___-___" },
  { flag: "🇱🇰", code: "+94", name: "Sri Lanka", mask: "___ ___-____" },
  { flag: "🇳🇵", code: "+977", name: "Nepal", mask: "___-_______" },
  { flag: "🇲🇻", code: "+960", name: "Maldives", mask: "___-____" },
  { flag: "🇧🇹", code: "+975", name: "Bhutan", mask: "___-____" },
  { flag: "🇲🇲", code: "+95", name: "Myanmar", mask: "___-___-___" },
  { flag: "🇰🇭", code: "+855", name: "Cambodia", mask: "___-___-___" },
  { flag: "🇱🇦", code: "+856", name: "Laos", mask: "___ __ __ ___" },
  { flag: "🇻🇳", code: "+84", name: "Vietnam", mask: "(___) ___-___" },
  { flag: "🇹🇭", code: "+66", name: "Thailand", mask: "__-___-____" },
  { flag: "🇲🇾", code: "+60", name: "Malaysia", mask: "___-___-____" },
  { flag: "🇸🇬", code: "+65", name: "Singapore", mask: "____-____" },
  { flag: "🇮🇩", code: "+62", name: "Indonesia", mask: "(___) ___-____" },
  { flag: "🇵🇭", code: "+63", name: "Philippines", mask: "(___) ___-____" },
  { flag: "🇧🇳", code: "+673", name: "Brunei", mask: "___-____" },
  { flag: "🇹🇼", code: "+886", name: "Taiwan", mask: "___-____-___" },
  { flag: "🇭🇰", code: "+852", name: "Hong Kong", mask: "____-____" },
  { flag: "🇲🇴", code: "+853", name: "Macau", mask: "____-____" },
].map((item) =>
  typeof item === "string" ? { flag: item, code: "+1", name: item } : item,
);
