// import { Database } from "@/types/supabase";

export const CURP_STATES: Record<string, string> = {
    AS: "Aguascalientes",
    BC: "Baja California",
    BS: "Baja California Sur",
    CC: "Campeche",
    CL: "Coahuila",
    CM: "Colima",
    CS: "Chiapas",
    CH: "Chihuahua",
    DF: "Ciudad de México",
    DG: "Durango",
    GT: "Guanajuato",
    GR: "Guerrero",
    HG: "Hidalgo",
    JC: "Jalisco",
    MC: "Estado de México",
    MN: "Michoacán",
    MS: "Morelos",
    NT: "Nayarit",
    NL: "Nuevo León",
    OC: "Oaxaca",
    PL: "Puebla",
    QT: "Querétaro",
    QR: "Quintana Roo",
    SP: "San Luis Potosí",
    SL: "Sinaloa",
    SR: "Sonora",
    TC: "Tabasco",
    TS: "Tamaulipas",
    TL: "Tlaxcala",
    VZ: "Veracruz",
    YN: "Yucatán",
    ZS: "Zacatecas",
    NE: "Nacido en el extranjero"
}
